### ISSUE TITLE
Open in existing window

### ISSUE THREAD

**Issue by kleinjm** [danielecook/Quiver-alfred#3]
This is a feature request, not a bug. I love the workflow and it is super helpful but I find that I'm left with a lot of windows. Anyway to open the note in an existing window?

I saw that you're using the Mac Unix `open` (`open quiver:///notes/{query}`) so I'm guessing that you'd need to do some hacking on quiver itself to achieve this functionality.

Please let me know if you know where to look and need help.

**Comment by danielecook** [comment]
Yeah unfortunately not much I can do about it although I would like to. I played around with `open` for a bit and couldn't find anything, except when you use the -N option it will open a brand new copy of Quiver, and an additional window. Both will have the appropriate note selected.

**Comment by kleinjm** [comment]
Hmm alright. Good to know that you've looked into it before. Thanks again for the awesome plugin.

**Comment by danielecook** [comment]
No problem. If you have any other suggestions feel free to let me know!
